/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VendorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Organization.VendorOrganization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AddProductWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kesha
 */
public class AddProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddProduct
     */
    Product product;
    UserAccount account;
    Enterprise enterprise;
    JPanel userProcessContainer;
    JPanel backGroundJPanel;
    VendorOrganization organization;
    String path;
    EcoSystem business;

    public AddProduct(JPanel backGroundJPanel, JPanel userProcessContainer, UserAccount account, VendorOrganization organization, Enterprise enterprise,EcoSystem business) {

        initComponents();
        this.account = account;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.backGroundJPanel = backGroundJPanel;
        this.business=business;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        mBrand = new javax.swing.JTextField();
        mModel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mPrice = new javax.swing.JTextField();
        mQty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mCat = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mDescription = new javax.swing.JTextArea();
        selectedPhoto = new javax.swing.JLabel();
        mPhotoPath = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        photoSelection = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setMinimumSize(new java.awt.Dimension(1680, 980));
        setPreferredSize(new java.awt.Dimension(1680, 980));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 114, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Product Details");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 1200, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 153, 255));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 96, 200, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Brand:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 104, -1));

        mBrand.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mBrand.setForeground(new java.awt.Color(0, 153, 0));
        mBrand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        mBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBrandActionPerformed(evt);
            }
        });
        add(mBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 155, 180, -1));

        mModel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mModel.setForeground(new java.awt.Color(0, 153, 0));
        mModel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        mModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModelActionPerformed(evt);
            }
        });
        add(mModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 195, 180, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Model:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 195, 104, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Price:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 235, 104, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Quantity:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 275, 104, -1));

        mPrice.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mPrice.setForeground(new java.awt.Color(0, 153, 0));
        mPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        mPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPriceActionPerformed(evt);
            }
        });
        add(mPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 235, 180, -1));

        mQty.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mQty.setForeground(new java.awt.Color(0, 153, 0));
        mQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        mQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mQtyActionPerformed(evt);
            }
        });
        add(mQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 275, 180, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Category:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 315, 104, -1));

        mCat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mCat.setForeground(new java.awt.Color(0, 153, 0));
        mCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Mobiles", "Kids" }));
        mCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCatActionPerformed(evt);
            }
        });
        add(mCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 315, 180, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Product Description:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 355, 140, -1));

        mDescription.setColumns(20);
        mDescription.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mDescription.setForeground(new java.awt.Color(0, 153, 0));
        mDescription.setLineWrap(true);
        mDescription.setRows(5);
        mDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 0), java.awt.Color.gray));
        jScrollPane1.setViewportView(mDescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 365, 370, 190));

        selectedPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Add_Image_100px.png"))); // NOI18N
        selectedPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        selectedPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(selectedPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 230, 210));

        mPhotoPath.setEditable(false);
        mPhotoPath.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mPhotoPath.setForeground(new java.awt.Color(0, 153, 0));
        mPhotoPath.setText("Choose photo:");
        mPhotoPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        mPhotoPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPhotoPathActionPerformed(evt);
            }
        });
        add(mPhotoPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 120, 30));

        Update.setBackground(new java.awt.Color(0, 153, 51));
        Update.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Add Product");
        Update.setBorder(null);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 130, 40));

        photoSelection.setBackground(new java.awt.Color(0, 153, 0));
        photoSelection.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        photoSelection.setForeground(new java.awt.Color(0, 153, 0));
        photoSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Add_Camera_20px.png"))); // NOI18N
        photoSelection.setBorder(null);
        photoSelection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        photoSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoSelectionActionPerformed(evt);
            }
        });
        add(photoSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 50, 30));

        back.setBackground(new java.awt.Color(0, 153, 0));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("< Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mBrandActionPerformed

    private void mModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mModelActionPerformed

    private void mPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPriceActionPerformed

    private void mQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mQtyActionPerformed

    private void mCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCatActionPerformed

    private void mPhotoPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPhotoPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPhotoPathActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        product = new Product();
       
            
        product.setBrand_name(mBrand.getText());
        product.setCategoryName(mCat.getSelectedItem().toString());
        ArrayList<String> description = new ArrayList<>();
        description.add(mDescription.getText());
        product.setDescription(description);
        product.setModel(mModel.getText());
        product.setImageFileName(path);
        if(product.getBrand_name().isEmpty()||product.getModel().isEmpty()){
            JOptionPane.showMessageDialog(null, "Brandname/Model cannot be empty");
            return;
        }
        
       
        try{
        product.setPrice(Integer.valueOf(mPrice.getText()));
        product.setStock(Integer.valueOf(mQty.getText()));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Stock/Price must be a valid number");
            return;
        }
        
        product.setVendorName(account.getEmployee().getName());
//ArrayList<Product> productList=account.getEmployee().getProductsHashMap().get(product.getCategoryName());  
//productList.add(product);
        AddProductWorkRequest request = new AddProductWorkRequest();
        request.setSender(account);
        request.setProduct(product);
        request.setStatus("Initiated");
        request.setRequestType("Add Product");
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof InventoryOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
//enterprise.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Product add request sent to inventory");
        mBrand.setText("");
        mDescription.setText("");
        mPrice.setText("");
        mQty.setText("");
        mPhotoPath.setText("");
        mModel.setText("");

    }//GEN-LAST:event_UpdateActionPerformed

    private void photoSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoSelectionActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File selectedImage = fc.getSelectedFile();
        path = selectedImage.getName();

        try {
            Image img = ImageIO.read(selectedImage);
            mPhotoPath.setText(path);
            selectedPhoto.setIcon(new ImageIcon(img.getScaledInstance(selectedPhoto.getWidth(),
                    selectedPhoto.getHeight(), Image.SCALE_SMOOTH)));
        } catch (IOException ex) {

        }

    }//GEN-LAST:event_photoSelectionActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("VendorWorkArea", new VendorWorkAreaJPanel(backGroundJPanel, userProcessContainer, account, organization, enterprise,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mBrand;
    private javax.swing.JComboBox<String> mCat;
    private javax.swing.JTextArea mDescription;
    private javax.swing.JTextField mModel;
    private javax.swing.JTextField mPhotoPath;
    private javax.swing.JTextField mPrice;
    private javax.swing.JTextField mQty;
    private javax.swing.JButton photoSelection;
    private javax.swing.JLabel selectedPhoto;
    // End of variables declaration//GEN-END:variables
}
