/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InventoryRole;

import userinterface.VendorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InventoryOrganization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AddProductWorkRequest;

import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class InventoryWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private InventoryOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public InventoryWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InventoryOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business=business;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = request.getRequestID();
            row[1] = request.getRequestType();
            row[2] = request.getReceiver();
            row[3] = request.getRequestDate();
            row[4] = request.getSender();

//            String result = request.getStatus();
//            row[3] = result == null ? "Waiting" : result;
            row[5] = request.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AssignToMe = new javax.swing.JButton();
        Process = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setMinimumSize(new java.awt.Dimension(1680, 1050));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Request Type", "Receiver", "Request Date", "Sender", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 129, 514, 384));

        refreshTestJButton.setBackground(new java.awt.Color(0, 153, 0));
        refreshTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 37, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(38, 114, 0));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 27, 127, 30));

        valueLabel.setForeground(new java.awt.Color(0, 153, 0));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 27, 158, 26));

        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Work Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 107, -1, -1));

        AssignToMe.setBackground(new java.awt.Color(0, 153, 0));
        AssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        AssignToMe.setText("Assign to me");
        AssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignToMeActionPerformed(evt);
            }
        });
        add(AssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 519, -1, -1));

        Process.setBackground(new java.awt.Color(0, 153, 0));
        Process.setForeground(new java.awt.Color(255, 255, 255));
        Process.setText("Process");
        Process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessActionPerformed(evt);
            }
        });
        add(Process, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 519, 109, -1));

        remove.setBackground(new java.awt.Color(0, 153, 0));
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 519, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void AssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignToMeActionPerformed
        // TODO add your handling code here:int selectedRow = workRequestJTable.getSelectedRow();
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        int ID = (int) workRequestJTable.getValueAt(selectedRow, 0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request.getRequestID() == ID) {
                if (request.getStatus() == "Pending" || request.getStatus() == "Completed") {
                    JOptionPane.showMessageDialog(null, "Only unassigned requests can be assigned to you");
                    break;
                } else {
                    if (request.getSender().equals(userAccount)) {
                        JOptionPane.showMessageDialog(null, "Request sender and receiver cannot be same person!");
                    } else {
                        request.setReceiver(userAccount);
                        request.setStatus("Pending");
                        populateRequestTable();
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_AssignToMeActionPerformed

    private void ProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        int ID = (int) workRequestJTable.getValueAt(selectedRow, 0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request.getRequestID() == ID) {
                if (null == request.getReceiver() || (!request.getReceiver().equals(userAccount))) {
                    JOptionPane.showMessageDialog(null, "This request is not assigned to you");
                    break;
                } else {
                    if (request.getStatus().equals("Completed")) {
                        JOptionPane.showMessageDialog(null, "This request is already completed");
                        break;
                    } else {
                        if (request.getRequestType().equals("Stock Check")) {
                            StockCheckRequestJPanel stockCheckRequestJPanel = new StockCheckRequestJPanel(userProcessContainer, request, enterprise,business);
                            userProcessContainer.add("processWorkRequestJPanel", stockCheckRequestJPanel);
                            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                            layout.next(userProcessContainer);
                            break;
                        } else {
                            populateRequestTable();
                            ManageProductRequestJPanel addProductRequestJPanel = new ManageProductRequestJPanel(userProcessContainer, request);
                            userProcessContainer.add("processWorkRequestJPanel", addProductRequestJPanel);
                            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                            layout.next(userProcessContainer);
                            break;
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_ProcessActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        int ID = (int) workRequestJTable.getValueAt(selectedRow, 0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request.getRequestID() == ID) {
                organization.getWorkQueue().getWorkRequestList().remove(request);
                populateRequestTable();
                break;
            }
        }

    }//GEN-LAST:event_removeActionPerformed

    private HashMap<String, ArrayList<Product>> ReadFromProductsExcel(String pathToCsv) throws FileNotFoundException, IOException {
        String[] categoryArray = {"Newly Added", "Electronics", "Mobiles", "Kids Corner"};
        String[] collections = {"products", "productCategory"};
        HashMap<String, ArrayList<Product>> productsListMap = new HashMap<String, ArrayList<Product>>();
        String row = "";
        BufferedReader csvReader = new BufferedReader(new FileReader(pathToCsv));
        int rowCount = 0;
        Product lastAddedProduct = null;
        while ((row = csvReader.readLine()) != null) {
            if (rowCount == 0) {
                rowCount++;
                continue;
            }
            String[] data = row.split(",");
            if (data.length == 1) {
                lastAddedProduct.getDescription().add(data[0]);
                continue;
            }
            if (data.length == 2) {
                lastAddedProduct.getDescription().add(data[0] + " " + data[1]);
                continue;
            }
            String category = data[6];
            // DBObject dbObject = getDocumentByProperty(categoryCol, "name", category);
            // String id = dbObject.get("_id").toString();
            Product product = new Product();
            product.setBrand_name(data[1]);
            //  product.setCategoryId(id);
            product.getDescription().add(data[7]);
            product.setImageFileName(data[5]);
            product.setModel(data[2]);
            product.setPrice(Integer.parseInt(data[3]));
            product.setStock(Integer.parseInt(data[4]));
            if (productsListMap.containsKey(category)) {
                ArrayList<Product> arrayList = productsListMap.get(category);
                arrayList.add(product);
                lastAddedProduct = product;
            } else {
                ArrayList<Product> arrayList = new ArrayList<Product>();
                arrayList.add(product);
                lastAddedProduct = product;
                productsListMap.put(category, arrayList);
            }
            rowCount++;
            // do something with the data
        }
        csvReader.close();
        return productsListMap;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignToMe;
    private javax.swing.JButton Process;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton remove;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
