/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryRole;

import userinterface.VendorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DeliveryOrganization;
import Business.Organization.PaymentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

import Business.WorkQueue.OrderProcessWorkRequest;
import Business.WorkQueue.WorkRequest;
import Utilities.Address;
import Utilities.Email;
import Utilities.Maps;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class ProcessRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DeliveryOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private WorkRequest request;
    private int deliverydays;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public ProcessRequestJPanel(JPanel userProcessContainer, UserAccount account, DeliveryOrganization organization, Enterprise enterprise,EcoSystem business,WorkRequest request )  {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business=business;
        this.request=request;
        
        
        initialize();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        distance = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressfield = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        days = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(1680, 1050));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(0, 153, 0));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Address");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Delivery Details");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 360, 80));

        distance.setEditable(false);
        distance.setForeground(new java.awt.Color(0, 153, 0));
        add(distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 70, -1));

        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Distance from inventory");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, 20));

        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Kms");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, -1, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mark as Complete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        addressfield.setEditable(false);
        addressfield.setForeground(new java.awt.Color(0, 153, 0));
        jScrollPane1.setViewportView(addressfield);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 260, 70));

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("No of Days to deliver");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        days.setForeground(new java.awt.Color(0, 153, 0));
        add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 40, -1));

        updateBtn.setBackground(new java.awt.Color(0, 153, 0));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DeliveryWorkAreaJPanel dwjp = (DeliveryWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        request.setStatus("Delivered");
        JOptionPane.showMessageDialog(null, "Order status changed to delivered");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         OrderProcessWorkRequest paymentProcessWorkRequest=(OrderProcessWorkRequest) request;
        try{
       //deliverydays=Integer.valueOf(days.getText());
      paymentProcessWorkRequest.getOrder().setEstDelivery(Integer.valueOf(days.getText()));
       JOptionPane.showMessageDialog(null, "Estimated delivery date updated and customer notified");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "value must be a number");
        }
       
        try {
            Email.sendMail(paymentProcessWorkRequest.getOrder().getEmail(), "Hello "+paymentProcessWorkRequest.getOrder().getFullname()+"\n\tYour order will be delivered in "+days.getText().toString()+" days", "ShopEasy Order status");
        } catch (MessagingException ex) {
           JOptionPane.showMessageDialog(null, "Exception in sending mail "+ex.getMessage());
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane addressfield;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField days;
    private javax.swing.JTextField distance;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void initialize() {
        try {
            OrderProcessWorkRequest paymentProcessWorkRequest=(OrderProcessWorkRequest)request;
            
            Address address=Maps.getAddressDistance(paymentProcessWorkRequest.getOrder().getShippingAddress());
            addressfield.setText(address.getAddress());
            distance.setText(String.valueOf(address.getDistance()));
            
            days.setText(String.valueOf(paymentProcessWorkRequest.getOrder().getEstDelivery()));
        
        } catch (IOException ex) {
            Logger.getLogger(ProcessRequestJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
