/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Person.Person;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Product.Product;
import Business.Role.AdminRole;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;
import userinterface.CustomerRole.CustomerWorkAreaJPanel;

/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount account;
    final static Logger logger = Logger.getLogger(CustomerWorkAreaJPanel.class);
    
    public MainJFrame() {
        BasicConfigurator.configure();
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setSize(980, 980);
        this.setTitle("Inventory Management System");
        initialize();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBackgroundJPanel = new javax.swing.JPanel();
        titleMainHorrJPanel = new javax.swing.JPanel();
        invMgtJLabel = new javax.swing.JLabel();
        invIconJLabel = new javax.swing.JLabel();
        loggedinasJLabel = new javax.swing.JLabel();
        logginAnsJLabel = new javax.swing.JLabel();
        logOutjButton = new javax.swing.JButton();
        cardParentJPanel = new javax.swing.JPanel();
        signInPanel = new javax.swing.JPanel();
        signInFirstJPanel = new javax.swing.JPanel();
        signInJLabel = new javax.swing.JLabel();
        signinIconJLabel = new javax.swing.JLabel();
        signInSecondJPanel = new javax.swing.JPanel();
        usernameJLabel = new javax.swing.JLabel();
        usernameJSeparator = new javax.swing.JSeparator();
        userNameJTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        passwordJSeparator = new javax.swing.JSeparator();
        havenotsignupJLabel = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        signInJButton = new javax.swing.JButton();
        signUpWordButton = new javax.swing.JButton();
        showPassword1 = new javax.swing.JCheckBox();
        warningLabel = new javax.swing.JTextField();
        signUpPanel = new javax.swing.JPanel();
        signUpSecondJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        namejSeparator = new javax.swing.JSeparator();
        signUpNameField = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        emailjSeparator = new javax.swing.JSeparator();
        signUpEmailField = new javax.swing.JTextField();
        emptyField = new javax.swing.JLabel();
        usernamejSeparator = new javax.swing.JSeparator();
        passJLabel = new javax.swing.JLabel();
        passwordjSeparator = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        signUpPasswordField = new javax.swing.JPasswordField();
        signInWordButton = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();
        signUpJButton = new javax.swing.JButton();
        signUpUsernameField = new javax.swing.JTextField();
        useernameJLabel = new javax.swing.JLabel();
        usernameExists = new javax.swing.JLabel();
        passJLabel1 = new javax.swing.JLabel();
        networkCombo = new javax.swing.JComboBox<>();
        signUpFirstJPanel = new javax.swing.JPanel();
        signUPJlabel = new javax.swing.JLabel();
        accJLabelPic = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        setMinimumSize(new java.awt.Dimension(1680, 980));
        getContentPane().setLayout(new java.awt.CardLayout());

        mainBackgroundJPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainBackgroundJPanel.setMinimumSize(new java.awt.Dimension(1680, 1050));
        mainBackgroundJPanel.setPreferredSize(new java.awt.Dimension(1680, 980));
        mainBackgroundJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleMainHorrJPanel.setBackground(new java.awt.Color(0, 153, 0));
        titleMainHorrJPanel.setMinimumSize(new java.awt.Dimension(1680, 1050));
        titleMainHorrJPanel.setPreferredSize(new java.awt.Dimension(1680, 70));
        titleMainHorrJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invMgtJLabel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        invMgtJLabel.setForeground(new java.awt.Color(255, 255, 255));
        invMgtJLabel.setText("ShopEasy");
        invMgtJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invMgtJLabelMouseClicked(evt);
            }
        });
        titleMainHorrJPanel.add(invMgtJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 620, -1));

        invIconJLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleMainHorrJPanel.add(invIconJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 51, 81));
        invIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Shopping_Bag_48px.png")));

        loggedinasJLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        loggedinasJLabel.setForeground(new java.awt.Color(255, 255, 255));
        loggedinasJLabel.setText("Welcome");
        titleMainHorrJPanel.add(loggedinasJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 20, -1, 20));

        logginAnsJLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        logginAnsJLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleMainHorrJPanel.add(logginAnsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 10, 140, 40));

        logOutjButton.setBackground(new java.awt.Color(250, 250, 250));
        logOutjButton.setForeground(new java.awt.Color(0, 102, 51));
        logOutjButton.setText("Log Out");
        logOutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutjButtonActionPerformed(evt);
            }
        });
        titleMainHorrJPanel.add(logOutjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 20, -1, -1));

        mainBackgroundJPanel.add(titleMainHorrJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardParentJPanel.setBackground(new java.awt.Color(250, 250, 250));
        cardParentJPanel.setMinimumSize(new java.awt.Dimension(1680, 980));
        cardParentJPanel.setPreferredSize(new java.awt.Dimension(1680, 1050));
        cardParentJPanel.setLayout(new java.awt.CardLayout());

        signInPanel.setPreferredSize(new java.awt.Dimension(1680, 900));
        signInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInFirstJPanel.setBackground(new java.awt.Color(221, 224, 220));
        signInFirstJPanel.setPreferredSize(new java.awt.Dimension(460, 980));

        signInJLabel.setBackground(new java.awt.Color(0, 153, 0));
        signInJLabel.setFont(new java.awt.Font("Roboto Light", 0, 30)); // NOI18N
        signInJLabel.setForeground(new java.awt.Color(0, 153, 0));
        signInJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInJLabel.setText("Sign In.");

        signinIconJLabel.setBackground(new java.awt.Color(0, 0, 0));
        signinIconJLabel.setForeground(new java.awt.Color(204, 255, 204));
        signinIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/GreenLogin.png")));

        javax.swing.GroupLayout signInFirstJPanelLayout = new javax.swing.GroupLayout(signInFirstJPanel);
        signInFirstJPanel.setLayout(signInFirstJPanelLayout);
        signInFirstJPanelLayout.setHorizontalGroup(
            signInFirstJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInFirstJPanelLayout.createSequentialGroup()
                .addGroup(signInFirstJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInFirstJPanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(signinIconJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signInFirstJPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(signInJLabel)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        signInFirstJPanelLayout.setVerticalGroup(
            signInFirstJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInFirstJPanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(signinIconJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signInJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );

        signInPanel.add(signInFirstJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        signInSecondJPanel.setBackground(new java.awt.Color(250, 250, 250));
        signInSecondJPanel.setForeground(new java.awt.Color(0, 153, 0));
        signInSecondJPanel.setPreferredSize(new java.awt.Dimension(1220, 980));
        signInSecondJPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signInSecondJPanelFocusGained(evt);
            }
        });
        signInSecondJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                signInSecondJPanelComponentShown(evt);
            }
        });
        signInSecondJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameJLabel.setBackground(new java.awt.Color(0, 153, 0));
        usernameJLabel.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        usernameJLabel.setForeground(new java.awt.Color(0, 153, 0));
        usernameJLabel.setText("Username");
        signInSecondJPanel.add(usernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        usernameJSeparator.setBackground(new java.awt.Color(51, 153, 0));
        usernameJSeparator.setForeground(new java.awt.Color(0, 153, 0));
        usernameJSeparator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usernameJSeparator.setOpaque(true);
        usernameJSeparator.setPreferredSize(new java.awt.Dimension(310, 2));
        signInSecondJPanel.add(usernameJSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        userNameJTextField.setBackground(new java.awt.Color(250, 250, 250));
        userNameJTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        userNameJTextField.setForeground(new java.awt.Color(0, 153, 0));
        userNameJTextField.setBorder(null);
        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });
        userNameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameJTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameJTextFieldKeyPressed(evt);
            }
        });
        signInSecondJPanel.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 310, 50));

        passwordJLabel.setBackground(new java.awt.Color(0, 153, 0));
        passwordJLabel.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        passwordJLabel.setForeground(new java.awt.Color(0, 153, 0));
        passwordJLabel.setText("Password");
        signInSecondJPanel.add(passwordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        passwordJSeparator.setBackground(new java.awt.Color(51, 153, 0));
        passwordJSeparator.setForeground(new java.awt.Color(0, 153, 0));
        passwordJSeparator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordJSeparator.setOpaque(true);
        signInSecondJPanel.add(passwordJSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 310, 2));

        havenotsignupJLabel.setBackground(new java.awt.Color(0, 153, 0));
        havenotsignupJLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        havenotsignupJLabel.setForeground(new java.awt.Color(0, 153, 0));
        havenotsignupJLabel.setText("Haven't signed up?");
        signInSecondJPanel.add(havenotsignupJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        passwordJPasswordField.setBackground(new java.awt.Color(250, 250, 250));
        passwordJPasswordField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        passwordJPasswordField.setForeground(new java.awt.Color(0, 153, 0));
        passwordJPasswordField.setBorder(null);
        passwordJPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordJPasswordFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordJPasswordFieldKeyPressed(evt);
            }
        });
        signInSecondJPanel.add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 310, 50));

        signInJButton.setBackground(new java.awt.Color(0, 153, 0));
        signInJButton.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        signInJButton.setForeground(new java.awt.Color(255, 255, 255));
        signInJButton.setText("Sign In");
        signInJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInJButtonActionPerformed(evt);
            }
        });
        signInSecondJPanel.add(signInJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 130, 50));
        signInJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px.png")));

        signUpWordButton.setBackground(new java.awt.Color(0, 153, 0));
        signUpWordButton.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        signUpWordButton.setForeground(new java.awt.Color(0, 153, 0));
        signUpWordButton.setText("Sign Up Now.");
        signUpWordButton.setToolTipText("Sign In with your existed credentials.");
        signUpWordButton.setBorderPainted(false);
        signUpWordButton.setContentAreaFilled(false);
        signUpWordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpWordButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signUpWordButton.setPreferredSize(new java.awt.Dimension(130, 30));
        signUpWordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpWordButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpWordButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpWordButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signUpWordButtonMouseReleased(evt);
            }
        });
        signUpWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpWordButtonActionPerformed(evt);
            }
        });
        signInSecondJPanel.add(signUpWordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 502, 150, -1));
        signUpWordButton.getAccessibleContext().setAccessibleName("Sign Up Now");

        showPassword1.setBackground(new java.awt.Color(250, 250, 250));
        showPassword1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        showPassword1.setForeground(new java.awt.Color(0, 153, 0));
        showPassword1.setToolTipText("Show/Hide Password");
        showPassword1.setBorderPaintedFlat(true);
        showPassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassword1.setPreferredSize(new java.awt.Dimension(30, 30));
        showPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword1ActionPerformed(evt);
            }
        });
        signInSecondJPanel.add(showPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 20, 20));

        warningLabel.setBackground(new java.awt.Color(250, 250, 250));
        warningLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        warningLabel.setBorder(null);
        warningLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningLabelActionPerformed(evt);
            }
        });
        signInSecondJPanel.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 310, 50));

        signInPanel.add(signInSecondJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        cardParentJPanel.add(signInPanel, "card7");

        signUpPanel.setBackground(new java.awt.Color(250, 250, 250));
        signUpPanel.setMinimumSize(new java.awt.Dimension(1680, 980));
        signUpPanel.setPreferredSize(new java.awt.Dimension(1680, 900));
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpSecondJPanel.setBackground(new java.awt.Color(250, 250, 250));
        signUpSecondJPanel.setForeground(new java.awt.Color(177, 108, 246));
        signUpSecondJPanel.setMinimumSize(new java.awt.Dimension(963, 532));
        signUpSecondJPanel.setPreferredSize(new java.awt.Dimension(1220, 900));
        signUpSecondJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameJLabel.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        nameJLabel.setForeground(new java.awt.Color(0, 153, 0));
        nameJLabel.setText("Name");
        signUpSecondJPanel.add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        namejSeparator.setBackground(new java.awt.Color(0, 153, 51));
        namejSeparator.setForeground(new java.awt.Color(255, 255, 255));
        namejSeparator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namejSeparator.setOpaque(true);
        signUpSecondJPanel.add(namejSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 310, 2));

        signUpNameField.setBackground(new java.awt.Color(250, 250, 250));
        signUpNameField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        signUpNameField.setForeground(new java.awt.Color(0, 153, 0));
        signUpNameField.setBorder(null);
        signUpNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpNameFieldActionPerformed(evt);
            }
        });
        signUpSecondJPanel.add(signUpNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 310, 50));

        emailJLabel.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        emailJLabel.setForeground(new java.awt.Color(0, 153, 0));
        emailJLabel.setText("Email");
        signUpSecondJPanel.add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        emailjSeparator.setBackground(new java.awt.Color(0, 153, 51));
        emailjSeparator.setForeground(new java.awt.Color(255, 255, 255));
        emailjSeparator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailjSeparator.setOpaque(true);
        signUpSecondJPanel.add(emailjSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 310, 2));

        signUpEmailField.setBackground(new java.awt.Color(250, 250, 250));
        signUpEmailField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        signUpEmailField.setForeground(new java.awt.Color(0, 153, 0));
        signUpEmailField.setBorder(null);
        signUpEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpEmailFieldActionPerformed(evt);
            }
        });
        signUpSecondJPanel.add(signUpEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 310, 50));

        emptyField.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        emptyField.setForeground(new java.awt.Color(255, 51, 0));
        signUpSecondJPanel.add(emptyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 270, 30));

        usernamejSeparator.setBackground(new java.awt.Color(0, 153, 51));
        usernamejSeparator.setForeground(new java.awt.Color(255, 255, 255));
        usernamejSeparator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usernamejSeparator.setOpaque(true);
        signUpSecondJPanel.add(usernamejSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 310, 2));

        passJLabel.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        passJLabel.setForeground(new java.awt.Color(0, 153, 0));
        passJLabel.setText("Network");
        signUpSecondJPanel.add(passJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        passwordjSeparator.setBackground(new java.awt.Color(0, 153, 51));
        passwordjSeparator.setForeground(new java.awt.Color(255, 255, 255));
        passwordjSeparator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordjSeparator.setOpaque(true);
        signUpSecondJPanel.add(passwordjSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 310, 2));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Already a member?");
        signUpSecondJPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        signUpPasswordField.setBackground(new java.awt.Color(250, 250, 250));
        signUpPasswordField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        signUpPasswordField.setForeground(new java.awt.Color(0, 153, 0));
        signUpPasswordField.setBorder(null);
        signUpSecondJPanel.add(signUpPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 310, 50));

        signInWordButton.setBackground(new java.awt.Color(255, 255, 255));
        signInWordButton.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        signInWordButton.setForeground(new java.awt.Color(0, 153, 0));
        signInWordButton.setText("Sign In.");
        signInWordButton.setToolTipText("Sign In with your existed credentials.");
        signInWordButton.setBorder(null);
        signInWordButton.setBorderPainted(false);
        signInWordButton.setContentAreaFilled(false);
        signInWordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInWordButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signInWordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInWordButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signInWordButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInWordButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInWordButtonMouseEntered(evt);
            }
        });
        signInWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInWordButtonActionPerformed(evt);
            }
        });
        signUpSecondJPanel.add(signInWordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 90, 30));

        showPassword.setBackground(new java.awt.Color(255, 255, 255));
        showPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        showPassword.setForeground(new java.awt.Color(0, 77, 64));
        showPassword.setToolTipText("Show/Hide Password");
        showPassword.setBorderPaintedFlat(true);
        showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassword.setPreferredSize(new java.awt.Dimension(30, 30));
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        signUpSecondJPanel.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 20, 20));

        signUpJButton.setBackground(new java.awt.Color(0, 153, 51));
        signUpJButton.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        signUpJButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpJButton.setText("Sign Up");
        signUpJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpJButton.setPreferredSize(new java.awt.Dimension(140, 50));
        signUpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpJButtonActionPerformed(evt);
            }
        });
        signUpSecondJPanel.add(signUpJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, -1, -1));
        signUpJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Checked_24px.png")));

        signUpUsernameField.setBackground(new java.awt.Color(250, 250, 250));
        signUpUsernameField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        signUpUsernameField.setForeground(new java.awt.Color(0, 153, 0));
        signUpUsernameField.setBorder(null);
        signUpUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpUsernameFieldActionPerformed(evt);
            }
        });
        signUpSecondJPanel.add(signUpUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 310, 50));

        useernameJLabel.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        useernameJLabel.setForeground(new java.awt.Color(0, 153, 0));
        useernameJLabel.setText("Username");
        signUpSecondJPanel.add(useernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        usernameExists.setBackground(new java.awt.Color(250, 250, 250));
        usernameExists.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        usernameExists.setForeground(new java.awt.Color(255, 51, 0));
        signUpSecondJPanel.add(usernameExists, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 160, 30));

        passJLabel1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        passJLabel1.setForeground(new java.awt.Color(0, 153, 0));
        passJLabel1.setText("Password");
        signUpSecondJPanel.add(passJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        signUpSecondJPanel.add(networkCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 320, -1));

        signUpPanel.add(signUpSecondJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        signUpFirstJPanel.setBackground(new java.awt.Color(221, 224, 220));
        signUpFirstJPanel.setMinimumSize(new java.awt.Dimension(460, 980));
        signUpFirstJPanel.setPreferredSize(new java.awt.Dimension(460, 900));
        signUpFirstJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUPJlabel.setFont(new java.awt.Font("Roboto Light", 0, 30)); // NOI18N
        signUPJlabel.setForeground(new java.awt.Color(0, 153, 0));
        signUPJlabel.setText("Sign Up!");
        signUpFirstJPanel.add(signUPJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));
        signUpFirstJPanel.add(accJLabelPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, 160));
        accJLabelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Accounts_main_180x180.png")));
        signUpFirstJPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 168));

        signUpPanel.add(signUpFirstJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 980));

        cardParentJPanel.add(signUpPanel, "card6");

        mainBackgroundJPanel.add(cardParentJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        getContentPane().add(mainBackgroundJPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpNameFieldActionPerformed

    private void signUpEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpEmailFieldActionPerformed

    private void signInWordButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInWordButtonMouseEntered
        // TODO add your handling code here:
        signInWordButton.setForeground(new Color(48, 79, 254));
    }//GEN-LAST:event_signInWordButtonMouseEntered

    private void signInWordButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInWordButtonMouseExited
        // TODO add your handling code here:
        signInWordButton.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_signInWordButtonMouseExited

    private void signInWordButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInWordButtonMousePressed
        // TODO add your handling code here:
        signInWordButton.setForeground(new Color(18, 5, 128));
    }//GEN-LAST:event_signInWordButtonMousePressed

    private void signInWordButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInWordButtonMouseReleased
        // TODO add your handling code here:
        signInWordButton.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_signInWordButtonMouseReleased

    private void signInWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInWordButtonActionPerformed
        // TODO add your handling code here:

        cardParentJPanel.removeAll();
        cardParentJPanel.add(signInPanel);
        // cardParentPanel.repaint();
        //  cardParentPanel.revalidate();
        mainBackgroundJPanel.repaint();
        mainBackgroundJPanel.revalidate();
    }//GEN-LAST:event_signInWordButtonActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if (showPassword.isSelected()) {
            signUpPasswordField.setEchoChar((char) 0);
        } else {
            signUpPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed
    private boolean passwordPatternCorrect() {
        
        Pattern p = Pattern.compile("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@#*_])[A-Za-z\\d$*#&]{4,}$");
        Matcher m = p.matcher(signUpPasswordField.getText());
        boolean b = m.matches();
        return b;
    }
    
    private boolean emailPatternCorrect() {
        
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(signUpEmailField.getText());
        boolean b = m.matches();
        return b;
    }
    private void signUpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpJButtonActionPerformed
        // TODO add your handling code here:
        Enterprise marketEnterprise = system.getNetworkList().stream().filter(p -> p.getName().equals(networkCombo.getSelectedItem())).findAny().orElse(null).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getEnterpriseType().equals(Enterprise.EnterpriseType.Market)).findAny().orElse(null);
        Organization customerOrganization = marketEnterprise.getOrganizationDirectory().getOrganizationList().stream().filter(o -> o.getName().equals("Customer Organization")).findAny().orElse(null);
        Person customerEmployee1 = customerOrganization.getEmployeeDirectory().createEmployee(signUpUsernameField.getText());
        customerOrganization.getUserAccountDirectory().createCustomerUserAccount(signUpNameField.getText(), signUpEmailField.getText(), signUpUsernameField.getText(), signUpPasswordField.getText(), customerEmployee1, new CustomerRole());
        if (signUpNameField.getText() == null || signUpNameField.getText().equals("")) {
            signUpNameField.setForeground(Color.RED);
            logger.info("Name can't be empty. ");
            JOptionPane.showMessageDialog(null, "Name can't be empty. ");
            return;
        }
        if (signUpEmailField.getText() == null || signUpEmailField.getText().equals("")) {
            signUpEmailField.setForeground(Color.RED);
            logger.info("Email can't be empty. ");
            JOptionPane.showMessageDialog(null, "Email can't be empty. ");
            return;
        }
        
        if (!emailPatternCorrect()) {
            logger.info("Email should be form of xxx@xxxx.com");
            JOptionPane.showMessageDialog(null, "Email should be form of xxx@xxxx.com");
            signUpEmailField.setForeground(Color.RED);
            return;
        }
        if (signUpUsernameField.getText() == null || signUpUsernameField.getText().equals("")) {
            signUpUsernameField.setForeground(Color.RED);
            logger.info("Name can't be empty. ");
            JOptionPane.showMessageDialog(null, "Name can't be empty. ");
            return;
        }
        if (signUpPasswordField.getText() == null || signUpPasswordField.getText().equals("")) {
            // signUpPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
            signUpPasswordField.setForeground(Color.RED);
            logger.info("Password can't be empty. ");
            JOptionPane.showMessageDialog(null, "Password can't be empty. ");
            return;
        }
        if (!passwordPatternCorrect()) {
            logger.info("Password should be a combination of number, uppercarse, lowercase abd special character @,#,*,_ at least 4 characters long");
            JOptionPane.showMessageDialog(null, "Password should be a combination of number, uppercarse, lowercase abd special character @,#,*,_ at least 4 characters long");
            signUpPasswordField.setForeground(Color.RED);
            return;
            
        }
        
        dB4OUtil.storeSystem(system);
        logger.info("User Created Successfully! Please go ahead and sign in!");
        JOptionPane.showMessageDialog(null, "User Created Successfully! Please go ahead and sign in!");
        clearAllTextFields();
    }//GEN-LAST:event_signUpJButtonActionPerformed

    private void signUpUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpUsernameFieldActionPerformed

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void signInJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInJButtonActionPerformed
        // TODO add your handling code here:
        try {
            String userName = userNameJTextField.getText();
            // Get Password
            char[] passwordCharArray = passwordJPasswordField.getPassword();
            String password = String.valueOf(passwordCharArray);

            //Step1: Check in the system admin user account directory if you have the user
            UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
            
            Enterprise inEnterprise = null;
            Organization inOrganization = null;
            
            if (userAccount == null) {
                //Step 2: Go inside each network and check each enterprise
                for (Network network : system.getNetworkList()) {
                    //Step 2.a: check against each enterprise
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if (userAccount == null) {
                            //Step 3:check against each organization for each enterprise
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if (userAccount != null) {
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                    break;
                                }
                            }
                            
                        } else {
                            inEnterprise = enterprise;
                            break;
                        }
                        if (inOrganization != null) {
                            break;
                        }
                    }
                    if (inEnterprise != null) {
                        break;
                    }
                }
            }
            if (userNameJTextField.getText() == null || userNameJTextField.getText().equals("")) {
                // userNameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
                userNameJTextField.setForeground(Color.RED);
                logger.info("Username can't be empty. ");
                JOptionPane.showMessageDialog(null, "Username can't be empty. ");
                return;
            }
            if (passwordJPasswordField.getText() == null || passwordJPasswordField.getText().equals("")) {
                // passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
                passwordJPasswordField.setForeground(Color.RED);
                logger.info("Password can't be empty. ");
                JOptionPane.showMessageDialog(null, "Password can't be empty. ");
                return;
            }
            if (userAccount == null) {
                logger.info("Invalid Username or password! Please re-enter!");
                JOptionPane.showMessageDialog(null, "Invalid Username or password! Please re-enter!");
                //   usernameJSeparator.setBorder(BorderFactory.createLineBorder(Color.RED));
                userNameJTextField.setForeground(Color.RED);
                //   passwordJSeparator.setBorder(BorderFactory.createLineBorder(Color.RED));
                passwordJPasswordField.setForeground(Color.RED);
                return;
            } else {
                logginAnsJLabel.setText(userName);
                cardParentJPanel.removeAll();
                CardLayout layout = (CardLayout) cardParentJPanel.getLayout();
                cardParentJPanel.add("workArea", userAccount.getRole().createWorkArea(mainBackgroundJPanel, cardParentJPanel, userAccount, inOrganization, inEnterprise, system));
                mainBackgroundJPanel.repaint();
                mainBackgroundJPanel.revalidate();
            }

            //  loginJButton.setEnabled(false);
            //  logoutJButton.setEnabled(true);
            userNameJTextField.setEnabled(false);
            passwordJPasswordField.setEnabled(false);
        } catch (Exception e) {
            logger.error(e);
        }

    }//GEN-LAST:event_signInJButtonActionPerformed
    private void userNameJTextFieldMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        userNameJTextField.setForeground(new Color(0, 153, 0));//
    }
    private void signUpWordButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpWordButtonMouseEntered
        // TODO add your handling code here:
        signUpWordButton.setForeground(new Color(48, 79, 254));//
    }//GEN-LAST:event_signUpWordButtonMouseEntered

    private void signUpWordButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpWordButtonMouseExited
        // TODO add your handling code here:
        signUpWordButton.setForeground(new Color(85, 26, 139));//204,153,255
    }//GEN-LAST:event_signUpWordButtonMouseExited

    private void signUpWordButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpWordButtonMousePressed
        // TODO add your handling code here:
        signUpWordButton.setForeground(new Color(18, 5, 128));
    }//GEN-LAST:event_signUpWordButtonMousePressed

    private void signUpWordButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpWordButtonMouseReleased
        // TODO add your handling code here:
        signUpWordButton.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_signUpWordButtonMouseReleased

    private void signUpWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpWordButtonActionPerformed
        // TODO add your handling code here:
//
        cardParentJPanel.removeAll();
        cardParentJPanel.add(signUpPanel);
        
        mainBackgroundJPanel.repaint();
        mainBackgroundJPanel.revalidate();

    }//GEN-LAST:event_signUpWordButtonActionPerformed

    private void showPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword1ActionPerformed
        // TODO add your handling code here:
        if (showPassword1.isSelected()) {
            passwordJPasswordField.setEchoChar((char) 0);
        } else {
            passwordJPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassword1ActionPerformed

    private void warningLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warningLabelActionPerformed

    private void signInSecondJPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signInSecondJPanelFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_signInSecondJPanelFocusGained

    private void signInSecondJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_signInSecondJPanelComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_signInSecondJPanelComponentShown

    private void invMgtJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invMgtJLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_invMgtJLabelMouseClicked

    private void logOutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutjButtonActionPerformed
        // TODO add your handling code here:
        logginAnsJLabel.setText("");
        userNameJTextField.setEnabled(true);
        passwordJPasswordField.setEnabled(true);
        userNameJTextField.setText("");
        passwordJPasswordField.setText("");
        cardParentJPanel.removeAll();
        cardParentJPanel.add(signInPanel);
        mainBackgroundJPanel.repaint();
        mainBackgroundJPanel.revalidate();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logOutjButtonActionPerformed

    private void userNameJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameJTextFieldKeyPressed
        // TODO add your handling code here:
        userNameJTextField.setForeground(new Color(0, 153, 0));
    }//GEN-LAST:event_userNameJTextFieldKeyPressed

    private void userNameJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameJTextFieldKeyTyped
        // TODO add your handling code here:
        userNameJTextField.setForeground(new Color(0, 153, 0));
    }//GEN-LAST:event_userNameJTextFieldKeyTyped

    private void passwordJPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldKeyPressed
        // TODO add your handling code here:
        passwordJPasswordField.setForeground(new Color(0, 153, 0));
    }//GEN-LAST:event_passwordJPasswordFieldKeyPressed

    private void passwordJPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldKeyTyped
        // TODO add your handling code here:
        passwordJPasswordField.setForeground(new Color(0, 153, 0));
    }//GEN-LAST:event_passwordJPasswordFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accJLabelPic;
    private javax.swing.JPanel cardParentJPanel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JSeparator emailjSeparator;
    private javax.swing.JLabel emptyField;
    private javax.swing.JLabel havenotsignupJLabel;
    private javax.swing.JLabel invIconJLabel;
    private javax.swing.JLabel invMgtJLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JButton logOutjButton;
    private javax.swing.JLabel loggedinasJLabel;
    private javax.swing.JLabel logginAnsJLabel;
    private javax.swing.JPanel mainBackgroundJPanel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JSeparator namejSeparator;
    private javax.swing.JComboBox<String> networkCombo;
    private javax.swing.JLabel passJLabel;
    private javax.swing.JLabel passJLabel1;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JSeparator passwordJSeparator;
    private javax.swing.JSeparator passwordjSeparator;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JCheckBox showPassword1;
    private javax.swing.JPanel signInFirstJPanel;
    private javax.swing.JButton signInJButton;
    private javax.swing.JLabel signInJLabel;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JPanel signInSecondJPanel;
    private javax.swing.JButton signInWordButton;
    private javax.swing.JLabel signUPJlabel;
    private javax.swing.JTextField signUpEmailField;
    private javax.swing.JPanel signUpFirstJPanel;
    private javax.swing.JButton signUpJButton;
    private javax.swing.JTextField signUpNameField;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JPasswordField signUpPasswordField;
    private javax.swing.JPanel signUpSecondJPanel;
    private javax.swing.JTextField signUpUsernameField;
    private javax.swing.JButton signUpWordButton;
    private javax.swing.JLabel signinIconJLabel;
    private javax.swing.JPanel titleMainHorrJPanel;
    private javax.swing.JLabel useernameJLabel;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JLabel usernameExists;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JSeparator usernameJSeparator;
    private javax.swing.JSeparator usernamejSeparator;
    private javax.swing.JTextField warningLabel;
    // End of variables declaration//GEN-END:variables

    private void initialize() {
        for (Network network : system.getNetworkList()) {
            networkCombo.addItem(network.getName());
        }
        
    }
    
    private void clearAllTextFields() {
        signUpNameField.setText("");
        signUpEmailField.setText("");
        signUpPasswordField.setText("");
        signUpUsernameField.setText("");
    }
    
}
